import { BriefcaseBusiness, CirclePause, CirclePlay, Clock3, Plus, Square } from 'lucide-react'
import { useEffect,useMemo,useState,type FormEvent } from 'react'
import { addManual,listMyTimeEntries,listWorkProjects,pauseTimer,resumeTimer,startTimer,stopTimer,type TimeEntry,type WorkProject } from './workspaceService'
export function WorkspacePage(){const[projects,setProjects]=useState<WorkProject[]>([]),[entries,setEntries]=useState<TimeEntry[]>([]),[project,setProject]=useState(''),[task,setTask]=useState(''),[notes,setNotes]=useState(''),[billable,setBillable]=useState(true),[now,setNow]=useState(0),[error,setError]=useState<string|null>(null),[manual,setManual]=useState(false)
 const load=async()=>{const[p,e]=await Promise.all([listWorkProjects(),listMyTimeEntries()]);if(p.error||e.error)setError(p.error?.message??e.error?.message??null);setProjects(p.data??[]);setEntries(e.data??[])};useEffect(()=>{void Promise.all([listWorkProjects(),listMyTimeEntries()]).then(([p,e])=>{if(p.error||e.error)setError(p.error?.message??e.error?.message??null);setProjects(p.data??[]);setEntries(e.data??[])})},[]);useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[])
 const active=entries.find(x=>!x.ended_at),selected=projects.find(x=>x.id===project),seconds=active?active.accumulated_seconds+(active.status==='running'?Math.max(0,Math.floor((now-new Date(active.last_resumed_at).getTime())/1000)):0):0
 const totals=useMemo(()=>{const today=new Date();const day=entries.filter(x=>sameDay(new Date(x.started_at),today)).reduce((s,x)=>s+x.accumulated_seconds,0);const week=entries.filter(x=>(today.getTime()-new Date(x.started_at).getTime())<7*86400000).reduce((s,x)=>s+x.accumulated_seconds,0);const month=entries.filter(x=>new Date(x.started_at).getMonth()===today.getMonth()&&new Date(x.started_at).getFullYear()===today.getFullYear()).reduce((s,x)=>s+x.accumulated_seconds,0);return{day,week,month}},[entries])
 async function begin(){if(!project)return setError('Selecciona un proyecto.');setError(null);const{error:requestError}=await startTimer(project,task||null,notes,billable);if(requestError)return setError(requestError.message);setNotes('');await load()}
 async function action(kind:'pause'|'resume'|'stop'){if(!active)return;const result=kind==='pause'?await pauseTimer(active.id):kind==='resume'?await resumeTimer(active.id):await stopTimer(active.id,notes);if(result.error)return setError(result.error.message);if(kind==='stop')setNotes('');await load()}
 async function manualSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget),hours=Number(data.get('hours')),minutes=Number(data.get('minutes'));const result=await addManual(String(data.get('project')),String(data.get('task'))||null,String(data.get('date')),hours*60+minutes,String(data.get('notes')),data.get('billable')==='on');if(result.error)return setError(result.error.message);setManual(false);await load()}
 return <><header className="module-header module-header-row"><div><span className="eyebrow dark">MI JORNADA</span><h1>Escritorio de trabajo</h1><p>Registra el tiempo real dedicado a proyectos y tareas.</p></div><button className="new-button" onClick={()=>setManual(true)}><Plus size={17}/> Registro manual</button></header>{error&&<p className="auth-error">{error}</p>}<section className="work-summary"><Card label="Hoy" value={duration(totals.day)}/><Card label="Últimos 7 días" value={duration(totals.week)}/><Card label="Este mes" value={duration(totals.month)}/></section>
 <section className={`panel timer-card ${active?'timer-active':''}`}><div className="timer-display"><span>{active?.status==='paused'?'EN PAUSA':active?'TRABAJANDO':'LISTO PARA COMENZAR'}</span><strong>{duration(seconds,true)}</strong>{active&&<p>{active.projects?.folio} · {active.projects?.name}{active.project_tasks?.title?` / ${active.project_tasks.title}`:''}</p>}</div>{!active?<div className="timer-form"><label>Proyecto<select value={project} onChange={e=>{setProject(e.target.value);setTask('')}}><option value="">Selecciona…</option>{projects.map(p=><option value={p.id} key={p.id}>{p.folio} · {p.name}</option>)}</select></label><label>Tarea<select value={task} onChange={e=>setTask(e.target.value)}><option value="">Sin tarea específica</option>{selected?.project_tasks.filter(t=>t.status!=='completed').map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label><label className="timer-notes">Nota<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="¿En qué vas a trabajar?"/></label><label className="billable-check"><input type="checkbox" checked={billable} onChange={e=>setBillable(e.target.checked)}/> Tiempo facturable</label><button className="new-button" onClick={()=>void begin()}><CirclePlay size={18}/> Iniciar</button></div>:<div className="timer-controls"><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Nota al finalizar (opcional)"/>{active.status==='running'?<button onClick={()=>void action('pause')}><CirclePause/> Pausar</button>:<button onClick={()=>void action('resume')}><CirclePlay/> Continuar</button>}<button className="stop" onClick={()=>void action('stop')}><Square/> Finalizar</button></div>}</section>
 <section className="panel work-history"><div className="panel-header"><div><h2>Historial personal</h2><p>Tus sesiones más recientes</p></div></div>{entries.filter(x=>x.ended_at).length?<div className="work-list">{entries.filter(x=>x.ended_at).map(x=><div key={x.id}><span><BriefcaseBusiness size={17}/></span><div><strong>{x.projects?.name}</strong><small>{x.project_tasks?.title??'Trabajo general'} · {new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(x.started_at))}</small></div><b>{duration(x.accumulated_seconds)}</b><i>{x.billable?'Facturable':'Interno'}</i></div>)}</div>:<div className="analytics-empty"><Clock3/><strong>Aún no hay sesiones terminadas</strong></div>}</section>{manual&&<div className="modal-backdrop"><form className="modal-card" onSubmit={manualSubmit}><h2>Registrar tiempo manual</h2><label>Proyecto<select name="project" required><option value="">Selecciona…</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Fecha<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><div className="form-grid"><label>Horas<input name="hours" type="number" min="0" max="24" defaultValue="1"/></label><label>Minutos<input name="minutes" type="number" min="0" max="59" defaultValue="0"/></label></div><label>Notas<textarea name="notes" rows={3}/></label><label className="billable-check"><input name="billable" type="checkbox" defaultChecked/> Facturable</label><div className="modal-actions"><button type="button" className="period-button" onClick={()=>setManual(false)}>Cancelar</button><button className="new-button">Guardar</button></div></form></div>}</>}
function Card({label,value}:{label:string;value:string}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong></article>}function duration(total:number,clock=false){const h=Math.floor(total/3600),m=Math.floor(total%3600/60),s=total%60;return clock?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${h}h ${String(m).padStart(2,'0')}m`}function sameDay(a:Date,b:Date){return a.toDateString()===b.toDateString()}
