packages:
  - website
  - desktop

allowBuilds:
  core-js: set this to true or false
  electron: true
  electron-winstaller: true
  esbuild: true
onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
