import { Building2, FileText, Save } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { getBusinessSettings, updateBusinessSettings, type BusinessSettingsInput } from './settingsService'

const empty:BusinessSettingsInput={business_name:'DevDesdeCeroMX',legal_name:null,tax_id:null,email:null,phone:null,address:null,website:null,logo_url:null,currency:'MXN',default_tax:0,quote_validity_days:15,quote_terms:null,receipt_notes:null}

export function SettingsPage(){
 const[form,setForm]=useState(empty),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[saved,setSaved]=useState(false)
 useEffect(()=>{void getBusinessSettings().then(({data,error:requestError})=>{if(data)setForm(data);setError(requestError?.message??null);setLoading(false)})},[])
 const text=(key:keyof BusinessSettingsInput,value:string)=>setForm((current)=>({...current,[key]:value||null}))
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);setSaved(false);setError(null);const{error:requestError}=await updateBusinessSettings(form);setSaving(false);if(requestError)return setError(requestError.message);setSaved(true)}
 if(loading)return <section className="panel module-loading"><strong>Cargando configuración…</strong></section>
 return <><header className="module-header"><span className="eyebrow dark">SISTEMA</span><h1>Configuración</h1><p>Administra la identidad y los valores predeterminados de tu negocio.</p></header><form className="settings-layout" onSubmit={submit}><section className="panel settings-section"><Heading icon={<Building2/>} title="Identidad del negocio" detail="Estos datos aparecerán en cotizaciones, recibos y reportes."/><div className="form-grid"><label>Nombre comercial<input required value={form.business_name} onChange={(e)=>text('business_name',e.target.value)}/></label><label>Razón social<input value={form.legal_name??''} onChange={(e)=>text('legal_name',e.target.value)} placeholder="Opcional"/></label><label>RFC<input value={form.tax_id??''} onChange={(e)=>text('tax_id',e.target.value.toUpperCase())} placeholder="Opcional"/></label><label>Correo<input type="email" value={form.email??''} onChange={(e)=>text('email',e.target.value)} placeholder="Opcional"/></label><label>Teléfono<input value={form.phone??''} onChange={(e)=>text('phone',e.target.value)} placeholder="Opcional"/></label><label>Sitio web<input type="url" value={form.website??''} onChange={(e)=>text('website',e.target.value)} placeholder="https://"/></label></div><label>Domicilio<textarea rows={2} value={form.address??''} onChange={(e)=>text('address',e.target.value)} placeholder="Opcional"/></label><label>URL del logotipo<input type="url" value={form.logo_url??''} onChange={(e)=>text('logo_url',e.target.value)} placeholder="https://…"/></label></section><section className="panel settings-section"><Heading icon={<FileText/>} title="Documentos" detail="Define valores para cotizaciones y recibos."/><div className="form-grid"><label>Moneda<select value={form.currency} onChange={(e)=>text('currency',e.target.value)}><option value="MXN">MXN · Peso mexicano</option><option value="USD">USD · Dólar estadounidense</option></select></label><label>Impuesto predeterminado (%)<input type="number" min="0" max="100" step="0.01" value={form.default_tax} onChange={(e)=>setForm({...form,default_tax:Number(e.target.value)})}/></label><label>Días de vigencia<input type="number" min="1" max="365" value={form.quote_validity_days} onChange={(e)=>setForm({...form,quote_validity_days:Number(e.target.value)})}/></label></div><label>Condiciones para cotizaciones<textarea rows={4} value={form.quote_terms??''} onChange={(e)=>text('quote_terms',e.target.value)} placeholder="Se mostrarán al final de cada cotización"/></label><label>Nota para recibos<textarea rows={3} value={form.receipt_notes??''} onChange={(e)=>text('receipt_notes',e.target.value)} placeholder="Se mostrará en cada recibo"/></label>{error&&<p className="auth-error">{error}</p>}{saved&&<p className="settings-success">Configuración guardada correctamente.</p>}<div className="modal-actions"><button className="new-button" disabled={saving}><Save size={17}/>{saving?'Guardando…':'Guardar cambios'}</button></div></section></form></>
}
function Heading({icon,title,detail}:{icon:React.ReactNode;title:string;detail:string}){return <div className="settings-heading">{icon}<div><h2>{title}</h2><p>{detail}</p></div></div>}
