import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Filter } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { listActiveStaff } from '@/features/projects/projectService'
import { listCalendarTasks, type CalendarTask } from './calendarService'

const weekdays=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom']
const statusLabels={todo:'Pendiente',in_progress:'En proceso',review:'En revisión',completed:'Completada',blocked:'Bloqueada'}
const localKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
const parseDate=(value:string)=>new Date(`${value}T12:00:00`)

export function CalendarPage(){
 const [tasks,setTasks]=useState<CalendarTask[]>([]),[staff,setStaff]=useState<Array<{id:string;full_name:string|null}>>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[month,setMonth]=useState(()=>{const date=new Date();return new Date(date.getFullYear(),date.getMonth(),1)}),[project,setProject]=useState('all'),[assignee,setAssignee]=useState('all'),[status,setStatus]=useState('open')
 useEffect(()=>{void Promise.all([listCalendarTasks(),listActiveStaff()]).then(([tasksResult,staffResult])=>{setTasks(tasksResult.data??[]);setStaff((staffResult.data as Array<{id:string;full_name:string|null}>|null)??[]);setError(tasksResult.error?.message??staffResult.error?.message??null);setLoading(false)})},[])
 const projects=useMemo(()=>Array.from(new Map(tasks.map((task)=>[task.project_id,task.projects])).entries()),[tasks])
 const filtered=useMemo(()=>tasks.filter((task)=>(project==='all'||task.project_id===project)&&(assignee==='all'||(assignee==='none'?!task.assignee_id:task.assignee_id===assignee))&&(status==='all'||(status==='open'?task.status!=='completed':task.status===status))),[tasks,project,assignee,status])
 const cells=useMemo(()=>{const first=new Date(month),offset=(first.getDay()+6)%7,start=new Date(first);start.setDate(1-offset);return Array.from({length:42},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return date})},[month])
 const today=localKey(new Date()), upcoming=filtered.filter((task)=>task.due_date>=today).slice(0,8), overdue=filtered.filter((task)=>task.due_date<today&&task.status!=='completed')
 const changeMonth=(amount:number)=>setMonth((current)=>new Date(current.getFullYear(),current.getMonth()+amount,1))
 return <><header className="module-header module-header-row"><div><span className="eyebrow dark">OPERACIÓN</span><h1>Calendario</h1><p>Vencimientos, entregas y carga de trabajo del equipo.</p></div><button className="period-button calendar-today" onClick={()=>{const date=new Date();setMonth(new Date(date.getFullYear(),date.getMonth(),1))}}>Hoy</button></header>
 {error&&<p className="auth-error dashboard-error">{error}</p>}<section className="calendar-filters panel"><Filter size={17}/><select value={project} onChange={(e)=>setProject(e.target.value)}><option value="all">Todos los proyectos</option>{projects.map(([id,item])=><option value={id} key={id}>{item?.name||id}</option>)}</select><select value={assignee} onChange={(e)=>setAssignee(e.target.value)}><option value="all">Todos los responsables</option><option value="none">Sin asignar</option>{staff.map((person)=><option value={person.id} key={person.id}>{person.full_name||'Usuario activo'}</option>)}</select><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="open">Tareas abiertas</option><option value="all">Todos los estados</option>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></section>
 <section className="calendar-layout"><article className="panel calendar-panel"><div className="calendar-heading"><button onClick={()=>changeMonth(-1)} aria-label="Mes anterior"><ChevronLeft/></button><h2>{new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric'}).format(month)}</h2><button onClick={()=>changeMonth(1)} aria-label="Mes siguiente"><ChevronRight/></button></div>{loading?<div className="empty-table"><strong>Cargando calendario…</strong></div>:<div className="calendar-grid">{weekdays.map((day)=><strong className="calendar-weekday" key={day}>{day}</strong>)}{cells.map((date)=>{const key=localKey(date),dayTasks=filtered.filter((task)=>task.due_date===key),outside=date.getMonth()!==month.getMonth();return <div className={`calendar-day ${outside?'outside':''} ${key===today?'today':''}`} key={key}><span>{date.getDate()}</span><div>{dayTasks.slice(0,3).map((task)=><Link to="/projects" title={`${task.projects?.name}: ${task.title}`} className={`calendar-event priority-${task.priority} ${task.status==='completed'?'done':''}`} key={task.id}>{task.title}</Link>)}{dayTasks.length>3&&<small>+{dayTasks.length-3} más</small>}</div></div>})}</div>}</article>
 <aside className="calendar-aside"><article className="panel deadline-card overdue-card"><div className="deadline-title"><Clock3 size={18}/><div><strong>{overdue.length} atrasadas</strong><span>Requieren atención</span></div></div>{overdue.slice(0,4).map((task)=><TaskBrief task={task} key={task.id}/>)}</article><article className="panel deadline-card"><div className="deadline-title"><CalendarDays size={18}/><div><strong>Próximos vencimientos</strong><span>{upcoming.length} en la agenda</span></div></div>{upcoming.length?upcoming.map((task)=><TaskBrief task={task} key={task.id}/>):<p className="calendar-empty">No hay vencimientos próximos.</p>}</article></aside></section></>
}

function TaskBrief({task}:{task:CalendarTask}){return <Link to="/projects" className="task-brief"><span>{new Intl.DateTimeFormat('es-MX',{day:'2-digit',month:'short'}).format(parseDate(task.due_date))}</span><div><strong>{task.title}</strong><small>{task.projects?.name||'Proyecto'}</small></div></Link>}
