import { BarChart3, Compass, Laptop, MousePointerClick, RefreshCw, Smartphone, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { getWebsiteAnalytics, type AnalyticsData, type AnalyticsPeriod } from './analyticsService'

const empty:AnalyticsData={views:0,visitors:0,sessions:0,leads:0,previousViews:0,series:[],sources:[],devices:[],browsers:[],languages:[]}
const labels:Record<AnalyticsPeriod,string>={day:'Hoy',week:'Semana',month:'Mes',year:'Año'}
const deviceNames:Record<string,string>={desktop:'Computadora',mobile:'Celular',tablet:'Tablet',other:'Otro'}
export function AnalyticsPage(){const[period,setPeriod]=useState<AnalyticsPeriod>('month'),[data,setData]=useState(empty),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 useEffect(()=>{void getWebsiteAnalytics(period).then(setData).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))},[period])
 const choosePeriod=(key:AnalyticsPeriod)=>{setLoading(true);setError(null);setPeriod(key)}
 const conversion=data.visitors?data.leads/data.visitors*100:0,change=data.previousViews?((data.views-data.previousViews)/data.previousViews)*100:null,max=Math.max(...data.series.map(x=>x.views),1)
 return <><header className="module-header module-header-row"><div><span className="eyebrow dark">SITIO PÚBLICO</span><h1>Analítica web</h1><p>Conoce cómo descubren y utilizan tu página, sin almacenar direcciones IP.</p></div><div className="analytics-periods">{(Object.keys(labels) as AnalyticsPeriod[]).map(key=><button className={period===key?'active':''} onClick={()=>choosePeriod(key)} key={key}>{labels[key]}</button>)}</div></header>{error&&<p className="auth-error">No pudimos cargar la analítica: {error}</p>}
 <section className="metrics-grid analytics-metrics"><Metric icon={<BarChart3/>} label="Visitas" value={data.views} detail={change===null?'Sin periodo anterior':`${change>=0?'+':''}${change.toFixed(0)}% vs. periodo anterior`}/><Metric icon={<Users/>} label="Visitantes" value={data.visitors} detail={`${data.sessions} sesiones`}/><Metric icon={<MousePointerClick/>} label="Contactos" value={data.leads} detail={`${conversion.toFixed(1)}% de conversión`}/><Metric icon={<Smartphone/>} label="Dispositivo principal" value={deviceNames[data.devices[0]?.label]??'—'} detail={data.devices[0]?`${data.devices[0].value} visitas`:'Esperando datos'}/></section>
 <section className="panel analytics-chart"><div className="panel-header"><div><h2>Evolución de visitas</h2><p>{labels[period]} actual</p></div>{loading&&<RefreshCw className="spin" size={18}/>}</div>{data.series.length?<div className="analytics-bars">{data.series.map(point=><div key={point.bucket} title={`${point.views} visitas`}><span style={{height:`${Math.max(point.views/max*100,4)}%`}}/><small>{formatBucket(point.bucket,period)}</small></div>)}</div>:<Empty/>}</section>
 <section className="analytics-grid"><Breakdown title="Fuentes de tráfico" icon={<Compass/>} items={data.sources}/><Breakdown title="Dispositivos" icon={<Laptop/>} items={data.devices.map(x=>({...x,label:deviceNames[x.label]??x.label}))}/><Breakdown title="Navegadores" icon={<BarChart3/>} items={data.browsers}/><Breakdown title="Idiomas" icon={<Users/>} items={data.languages}/></section></>}
function Metric({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:number|string;detail:string}){return <article className="metric-card"><div className="metric-top"><span>{label}</span><div className="metric-icon">{icon}</div></div><strong>{value}</strong><div className="metric-change neutral"><span>{detail}</span></div></article>}
function Breakdown({title,icon,items}:{title:string;icon:React.ReactNode;items:{label:string;value:number}[]}){const total=items.reduce((s,x)=>s+x.value,0)||1;return <article className="panel analytics-breakdown"><div className="settings-heading">{icon}<div><h2>{title}</h2><p>Distribución del periodo</p></div></div>{items.length?<div>{items.map(item=><div className="breakdown-row" key={item.label}><span>{item.label}</span><div><i style={{width:`${item.value/total*100}%`}}/><small>{item.value}</small></div></div>)}</div>:<Empty/>}</article>}
function Empty(){return <div className="analytics-empty"><strong>Aún no hay datos</strong><span>Las nuevas visitas aparecerán aquí.</span></div>}
function formatBucket(value:string,period:AnalyticsPeriod){const date=new Date(value);return period==='day'?new Intl.DateTimeFormat('es-MX',{hour:'numeric'}).format(date):period==='year'?new Intl.DateTimeFormat('es-MX',{month:'short'}).format(date):new Intl.DateTimeFormat('es-MX',{day:'2-digit',month:'short'}).format(date)}
