import { Activity, Filter, Search } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { listActivityAudit, type ActivityEntry } from './activityService'

const entityLabels:Record<string,string>={prospects:'Prospecto',clients:'Cliente',quotes:'Cotización',projects:'Proyecto',project_payments:'Pago',project_tasks:'Tarea',project_expenses:'Gasto',profile:'Usuario',business_settings:'Configuración'}
const actionLabels:Record<string,string>={created:'Creó',updated:'Actualizó',converted_to_client:'Convirtió a cliente',quote_accepted_project_created:'Aceptó cotización y creó proyecto',staff_updated:'Cambió permisos'}
const dateTime=new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'})

export function ActivityPage(){
 const[entries,setEntries]=useState<ActivityEntry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[search,setSearch]=useState(''),[entity,setEntity]=useState('all')
 useEffect(()=>{void listActivityAudit().then(({data,error:requestError})=>{setEntries(data??[]);setError(requestError?.message??null);setLoading(false)})},[])
 const entities=useMemo(()=>[...new Set(entries.map((entry)=>entry.entity_type))].sort(),[entries])
 const filtered=useMemo(()=>entries.filter((entry)=>(entity==='all'||entry.entity_type===entity)&&[entry.actor_name,entry.actor_email,actionLabels[entry.action]||entry.action,entityLabels[entry.entity_type]||entry.entity_type].some((value)=>value?.toLowerCase().includes(search.toLowerCase()))),[entries,search,entity])
 return <><header className="module-header"><span className="eyebrow dark">SISTEMA</span><h1>Historial de actividad</h1><p>Consulta los cambios importantes realizados dentro de DCX Manager.</p></header><section className="panel prospects-panel"><div className="prospects-toolbar activity-toolbar"><div className="search-field"><Search size={17}/><input placeholder="Buscar usuario, acción o módulo" value={search} onChange={(e)=>setSearch(e.target.value)}/></div><label><Filter size={15}/><select value={entity} onChange={(e)=>setEntity(e.target.value)}><option value="all">Todos los módulos</option>{entities.map((value)=><option value={value} key={value}>{entityLabels[value]||value}</option>)}</select></label><span>{filtered.length} movimientos</span></div>{error&&<p className="auth-error panel-error">{error}</p>}{loading?<div className="empty-table"><strong>Cargando actividad…</strong></div>:filtered.length?<div className="activity-list">{filtered.map((entry)=><article className="activity-row" key={entry.id}><div className="activity-icon"><Activity size={16}/></div><div><strong>{entry.actor_name||entry.actor_email||'Sistema'}</strong><span>{actionLabels[entry.action]||entry.action} · {entityLabels[entry.entity_type]||entry.entity_type}</span>{statusDetail(entry)}</div><time dateTime={entry.created_at}>{dateTime.format(new Date(entry.created_at))}</time></article>)}</div>:<div className="module-empty prospects-empty"><div className="module-empty-icon"><Activity size={27}/></div><h2>Sin movimientos para mostrar</h2><p>La actividad aparecerá aquí conforme se utilice el sistema.</p></div>}</section></>
}
function statusDetail(entry:ActivityEntry){const oldStatus=entry.metadata?.old_status,newStatus=entry.metadata?.new_status;if(typeof oldStatus==='string'||typeof newStatus==='string')return <small>{typeof oldStatus==='string'?oldStatus:'Sin estado'} → {typeof newStatus==='string'?newStatus:'Sin estado'}</small>;return null}
