create type public.time_entry_status as enum ('running','paused','completed');
create table public.time_entries (
  id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade, task_id uuid references public.project_tasks(id) on delete set null,
  status public.time_entry_status not null default 'running', started_at timestamptz not null default now(), last_resumed_at timestamptz not null default now(),
  accumulated_seconds integer not null default 0 check(accumulated_seconds>=0), ended_at timestamptz, notes text, billable boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index one_active_timer_per_user on public.time_entries(user_id) where ended_at is null;
create index time_entries_user_date_idx on public.time_entries(user_id,started_at desc);
create trigger time_entries_touch_updated_at before update on public.time_entries for each row execute function public.touch_updated_at();
alter table public.time_entries enable row level security;
create policy "Staff read own time" on public.time_entries for select to authenticated using (user_id=auth.uid() or public.is_administrator());
grant select on public.time_entries to authenticated;

create or replace function public.start_time_entry(p_project_id uuid,p_task_id uuid default null,p_notes text default null,p_billable boolean default true) returns public.time_entries language plpgsql security definer set search_path=public as $$ declare result public.time_entries; begin if not public.is_active_staff() then raise exception 'Sin acceso'; end if; if exists(select 1 from public.time_entries where user_id=auth.uid() and ended_at is null) then raise exception 'Ya tienes un temporizador activo'; end if; insert into public.time_entries(user_id,project_id,task_id,notes,billable) values(auth.uid(),p_project_id,p_task_id,nullif(trim(p_notes),''),p_billable) returning * into result; return result; end $$;
create or replace function public.pause_time_entry(p_entry_id uuid) returns public.time_entries language plpgsql security definer set search_path=public as $$ declare result public.time_entries; begin update public.time_entries set accumulated_seconds=accumulated_seconds+greatest(0,extract(epoch from(now()-last_resumed_at))::int),status='paused' where id=p_entry_id and user_id=auth.uid() and ended_at is null and status='running' returning * into result; if result.id is null then raise exception 'Temporizador no disponible'; end if; return result; end $$;
create or replace function public.resume_time_entry(p_entry_id uuid) returns public.time_entries language plpgsql security definer set search_path=public as $$ declare result public.time_entries; begin update public.time_entries set status='running',last_resumed_at=now() where id=p_entry_id and user_id=auth.uid() and ended_at is null and status='paused' returning * into result; if result.id is null then raise exception 'Temporizador no disponible'; end if; return result; end $$;
create or replace function public.stop_time_entry(p_entry_id uuid,p_notes text default null) returns public.time_entries language plpgsql security definer set search_path=public as $$ declare result public.time_entries; begin update public.time_entries set accumulated_seconds=accumulated_seconds+case when status='running' then greatest(0,extract(epoch from(now()-last_resumed_at))::int) else 0 end,status='completed',ended_at=now(),notes=coalesce(nullif(trim(p_notes),''),notes) where id=p_entry_id and user_id=auth.uid() and ended_at is null returning * into result; if result.id is null then raise exception 'Temporizador no disponible'; end if; return result; end $$;
create or replace function public.add_manual_time_entry(p_project_id uuid,p_task_id uuid,p_work_date date,p_minutes integer,p_notes text default null,p_billable boolean default true) returns public.time_entries language plpgsql security definer set search_path=public as $$ declare result public.time_entries; begin if not public.is_active_staff() or p_minutes<1 or p_minutes>1440 then raise exception 'Registro inválido'; end if; insert into public.time_entries(user_id,project_id,task_id,status,started_at,last_resumed_at,accumulated_seconds,ended_at,notes,billable) values(auth.uid(),p_project_id,p_task_id,'completed',p_work_date::timestamptz,p_work_date::timestamptz,p_minutes*60,p_work_date::timestamptz+(p_minutes||' minutes')::interval,nullif(trim(p_notes),''),p_billable) returning * into result; return result; end $$;
grant execute on function public.start_time_entry(uuid,uuid,text,boolean),public.pause_time_entry(uuid),public.resume_time_entry(uuid),public.stop_time_entry(uuid,text),public.add_manual_time_entry(uuid,uuid,date,integer,text,boolean) to authenticated;
